(function(){
    //TODO Create a gulp task which generates this file
    // generated by ng-constant
    'use strict';

    angular.module('myApp.dev')
        .constant('mocks', {useMocks:true});

}());